export const INIT_GLOBAL_DATA = 'INIT_GLOBAL_DATA';
export const GET_GLOBAL_MONTHLY_DATA = 'GET_GLOBAL_MONTHLY_DATA';

export const INIT_COUNTRY_LIST = 'INIT_COUNTRY_LIST';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';
